### ISSUE TITLE
peak detection

### ISSUE THREAD

**Issue by hsercanatli** [hsercanatli/tonic_identifier#4]
Optimize the peak detection algorithm parameters. For some examples It does not find all the peaks perfectly.

**Comment by sertansenturk** [comment]
have you tried the [function](https://github.com/altugkarakurt/ModeTonicRecognition/blob/master/PitchDistribution.py#L86) of from @altugkarakurt? Instead of self, you just have to give a numpy array (of the histogram)

**Comment by sertansenturk** [comment]
Switched to the essentia peak detection method
